notion_get_page:
  url: https://api.notion.com/v1/blocks/{{ page_id }}/children?page_size=100
  method: GET
  headers:
    authorization: !secret notion_integration_secret
    Notion-Version: "2022-06-28"
    accept: "application/json, text/html"
  verify_ssl: true
