# - platform: template
#   sensors:
#     office_motion_detection:
#       friendly_name: "Office Motion Detection"
#       value_template: >
#           {{ is_state('sun.sun', 'above_horizon') or is_state('group.family_sleep_status', 'on') }}
#       icon_template: >
#           mdi:motion-sensor