- platform: template
  sensors:
    paul_asleep:
      friendly_name: "Paul is asleep"
      value_template: >
          {{ is_state('binary_sensor.sm_g998b_bluetooth_state', 'off') and
             not is_state('sensor.sm_g998b_do_not_disturb_sensor', 'off') and
             not is_state('sensor.sm_g998b_do_not_disturb_sensor', 'unknown') }}
      icon_template: >
          mdi:sleep

- platform: template
  sensors:
    paul_home:
      friendly_name: "Paul is home"
      value_template: >
          {{ is_state('device_tracker.samsung_s21_ultra_von_paul', 'home') }}
      icon_template: >
          mdi:home