# - platform: template
#   sensors:
#     work_ongoing:
#       friendly_name: "Work ongoing"
#       value_template: >
#           {{ is_state('timer.work_timer', 'active') or is_state('timer.move_timer', 'active') }}
#       icon_template: >
#           mdi:hammer-wrench